services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile

    working_dir: /app

    ports:
      - "3000:3000"

    environment:
      JWT_SECRET: supersecret
      DATABASE_URL: file:/app/apps/backend/prisma/dev.db

    command: sh -c "pnpm --filter backend dev"